version: '3'

services:
  api_gateway:
    build: ./services/api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - intent_recognition_service
      - entity_extraction_service
      - dialog_manager_service
      - response_generation_service

  intent_recognition_service:
    build: ./services/intent_recognition
    ports:
      - "8001:8001"

  entity_extraction_service:
    build: ./services/entity_extraction
    ports:
      - "8002:8002"

  dialog_manager_service:
    build: ./services/dialog_manager
    ports:
      - "8003:8003"

  response_generation_service:
    build: ./services/response_generation
    ports:
      - "8004:8004"

  knowledge_base_service:
    build: ./services/knowledge_base
    ports:
      - "8005:8005"
