# Example deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: intent-recognition-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: intent-recognition
  template:
    metadata:
      labels:
        app: intent-recognition
    spec:
      containers:
      - name: intent-recognition
        image: your-docker-image
        ports:
        - containerPort: 8001
